# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install apt'able dependencies
    - name: Install zsh, expect, jq and youtube-dl
      run: |
        sudo apt install zsh expect jq youtube-dl

    - name: Install executables
      run: |
        mkdir --parent --verbose ~/bin
        wget -qO- 'https://github.com/junegunn/fzf-bin/releases/download/0.21.0/fzf-0.21.0-linux_amd64.tgz' | tar xz -C ~/bin
        curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > ~/bin/revolver
        curl -L https://github.com/zunit-zsh/zunit/releases/download/v0.8.2/zunit > ~/bin/zunit
        chmod +x ~/bin/*


    - name: Run tests
      run: |
        PATH=${HOME}/bin:${PATH} _PH_MARKS_PLUGIN_DIR=${PWD} unbuffer make test </dev/null
